# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: ${serverPort:8080}
  servlet:
    context-path: /${contextPath:}

# mysql
spring:
  # 环境 dev|test|prod
  profiles:
    active: ${envProfile:test}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

luckydb:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭

#mybatis
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.luckydb.model.entity

  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

swagger:
  enable: true

logging:
  level:
    com:
      luckydb:
        dao: debug
  config:
    classpath: logback-spring.xml


